common/models/PlaceReview.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "place_reviews".
 *
 * @property int $id
 * @property int $place_id
 * @property int $user_id
 * @property string $name
 * @property string $text
 * @property string $rating
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 */
class PlaceReview extends \yii\db\ActiveRecord
{
    public $features;
    
    const STATUS_BLOCKED    = 0;
    const STATUS_INACTIVE   = 5;
    const STATUS_ACTIVE     = 10;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'place_reviews';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'place_id', 'user_id'], 'required'],
            [['place_id', 'user_id', 'status'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['text'], 'string'],
            [['features'], 'safe'],
            [['rating'], 'number'],
        ];
    }

    /**
     * Relations
     */
    public function getPlace()
    {
        return $this->hasOne(Place::className(), ['id' => 'place_id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getScores()
    {
        return $this->hasMany(PlaceReviewScore::className(), ['review_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'place_id' => 'Заведение',
            'user_id' => 'Пользователь',
            'name' => 'Название',
            'text' => 'Текст',
            'rating' => 'Общий рейтинг',
            'status' => 'Статус',
            'created_at' => 'Дата добавления',
            'updated_at' => 'Дата обновления',
        ];
    }

    /**
     * Statuses
     */
    public function getStatusName() {
        switch ($this->status) {
            case self::STATUS_BLOCKED:
                return 'Отклонен';
                break;
            case self::STATUS_INACTIVE:
                return 'Неактивен';
                break;
            case self::STATUS_ACTIVE:
                return 'Активен';
                break;
            default:
                return '-';
                break;
        }
    }

    public function getStatusArr() {
        return [
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_INACTIVE => 'Неактивен',
        ];
    }

    public function saveScores()
    {
        // $total_score = 0;
        // $total_features = 0;
        if (is_array($this->features)) {
            PlaceReviewScore::deleteAll(['review_id' => $this->id]);
            foreach ($this->features as $feature => $score) {
                $place_review_score = new PlaceReviewScore();
                $place_review_score->review_id = $this->id;
                $place_review_score->feature = $feature;
                $place_review_score->score = $score;
                $place_review_score->save();
                // if ($place_review_score->save()) {
                //     $total_score += $score;
                //     $total_features += 1;
                // }
            }
            // $this->rating = round($total_score / $total_features, 2);
            // $this->save(false);
        }
        return true;
    }
}

common/models/PlaceView.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "place_views".
 *
 * @property int $id
 * @property int $place_id
 * @property int $user_id
 * @property int $created_at
 * @property int $updated_at
 */
class PlaceView extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'place_views';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['place_id', 'user_id'], 'required'],
            [['place_id', 'user_id'], 'integer'],
        ];
    }

    /**
     * Relations
     */
    public function getPlace()
    {
        return $this->hasOne(Place::className(), ['id' => 'place_id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'place_id' => 'Заведение',
            'user_id' => 'Пользователь',
            'created_at' => 'Дата добавления',
            'updated_at' => 'Дата обновления',
        ];
    }
}

backend/controllers/PlacesController.php
<?php

namespace backend\controllers;

use backend\models\PlacesSearch;
use backend\models\ReviewsSearch;
use common\models\Place;
use common\models\PlaceImage;
use common\models\PlaceOpeningHour;
use dastanaron\translit\Translit;
use himiklab\thumbnail\EasyThumbnailImage;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\imagine\Image;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * PlacesController implements the CRUD actions for Place model.
 */
class PlacesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'allow' => true,
						'roles' => ['admin', 'manager'],
					],
				]
			],
        ];
    }

    /**
     * Lists all Place models.
     * @return mixed
     */
    public function actionIndex()
    {
        // $place = Place::findOne(32);
        // $elastic_place = new ElasticPlace();
        // $elastic_place->attributes = [
        //     'id' => $place->id,
        //     'name' => $place->name,
        //     'address' => $place->address,
        //     'description' => $place->description,
        // ];
        // $elastic_place->primaryKey = $place->id;
        // $elastic_place->save();

        //$result = ElasticPlace::find()->query(['match' => ['id' => 32]])->all();
        //Yii::info(print_r($result, 1));

        $searchModel = new PlacesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionImport()
    {
        $translit = new Translit();
        $places = json_decode(file_get_contents('places.txt'), 1);
        // foreach ($places as $place) {
        //     $new_place = new Place();
        //     $new_place->id            = $place['id'];
        //     $new_place->name          = $place['name'];
        //     $new_place->alias         = $translit->translit($place['name'], false, 'ru-en');
        //     $new_place->user_id       = $place['user_id'];
        //     $new_place->city_id       = $place['city_id'];
        //     $new_place->district_id   = $place['district_id'];
        //     $new_place->network_id    = $place['chain_id'];
        //     // $new_place->coordinates   = $place['name'];
        //     $new_place->latitude      = $place['latitude'];
        //     $new_place->longitude     = $place['longitude'];
        //     $new_place->address       = $place['address'] ? $place['address'] : '-';
        //     $new_place->phone         = $place['phone'];
        //     $new_place->website       = $place['website'];
        //     $new_place->introtext     = $place['introtext'];
        //     $new_place->description   = $place['content'];
        //     $new_place->opening_hours = $place['opening_hours'];
        //     $new_place->rating        = $place['rate'];
        //     // $new_place->images_field  = $place['name'];
        //     // $new_place->comforts_field = $place['name'];
        //     // $new_place->metro_field   = $place['name'];
        //     // $new_place->similar_field = $place['name'];
        //     $new_place->total_views   = $place['views'];
        //     $new_place->total_likes   = $place['recommendations'];
        //     $new_place->status        = $place['status'];
        //     $new_place->created_at    = $place['created_at'];
        //     $new_place->updated_at    = $place['updated_at'];
        //     if (!$new_place->save()) {
        //         Yii::info(print_r($new_place->errors, 1));
        //     } else {
        //         for ($i = 2; $i < 100; $i++) { 
        //             $new_place->alias = $new_place->alias.$i;
        //             if ($new_place->save()) break;
        //         }
        //     }
        // }
        return count($places);
    }

    /**
     * Displays a single Place model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionViewReviews($id)
    {
        $model = $this->findModel($id);
        $searchModel = new ReviewsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('view-reviews', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionOpeningHours($id)
    {
        $model = $this->findModel($id);

        $opening_hours = Yii::$app->request->post('shedule-hour', []);
        if (count($opening_hours)) {
            PlaceOpeningHour::deleteAll(['place_id' => $id]);
            foreach ($opening_hours as $weekday => $opening_weeks) {
                foreach ($opening_weeks as $hour => $opening_week) {
                    $place_opening_hour = new PlaceOpeningHour();
                    $place_opening_hour->place_id = $id;
                    $place_opening_hour->weekday = $weekday;
                    $place_opening_hour->hour = $hour;
                    $place_opening_hour->save();
                }
            }
            return $this->redirect(Yii::$app->request->referrer);
        }

        return $this->render('opening-hours', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Place model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Place();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->uploadImages();
            $model->saveComforts();
            $model->saveSimilar();
            $model->saveMetro();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Place model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->comforts_field = ArrayHelper::getColumn($model->getPlaceComforts()->all(), 'comfort_id');
        $model->similar_field = ArrayHelper::getColumn($model->getPlaceSimilar()->all(), 'similar_id');
        $model->metro_field = ArrayHelper::getColumn($model->getPlaceMetro()->all(), 'metro_id');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->uploadImages();
            $model->saveComforts();
            $model->saveSimilar();
            $model->saveMetro();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an image of Product model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param $id
     * @return mixed
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDeleteImage($id)
    {
        if ($image = PlaceImage::findOne(['id' => $id]) and file_exists(Yii::getAlias('@frontend_web').$image->path)) {
            unlink(Yii::getAlias('@frontend_web').$image->path);
            return $image->delete();
        }
        return;
    }

    /**
     * @param $order
     * @return bool
     */
    public function actionSortImages($order)
    {
        foreach (explode(';', $order) as $key => $image_id) {
            $image = PlaceImage::findOne(['id' => $image_id]);
            $image->position = $key;
            $image->save();
        }
        return true;
    }

    /**
     * @param $id
     * @param int $angle
     * @return string|void
     * @throws \himiklab\thumbnail\FileNotFoundException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionRotateImage($id, $angle = 0)
    {
        if ($image_obj = PlaceImage::findOne($id)) {
            $image = Image::getImagine()->open(Yii::getAlias('@frontend_web').$image_obj->path);
            $image->rotate($angle)->save(Yii::getAlias('@frontend_web').$image_obj->path);
            return EasyThumbnailImage::thumbnailFileUrl(Yii::getAlias('@frontend_web').$image_obj->path, 160, 160, EasyThumbnailImage::THUMBNAIL_OUTBOUND);
        }
        return;
    }

    /**
     * Deletes an existing Place model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
		$model = $this->findModel($id);
		$model->status = Place::STATUS_DELETED;
		$model->save(false);
		return $this->redirect(['index']);
    }

    /**
     * Finds the Place model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Place the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Place::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/PlacesController.php
<?php

namespace frontend\controllers;

use common\models\Place;
use frontend\models\PlacesSearch;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * PlacesController implements the CRUD actions for Place model.
 */
class PlacesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
			
        ];
    }

    /**
     * Lists all Place models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PlacesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Place models for map.
     * @return mixed
     */
    public function actionMap()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return Place::find()->where(['city_id' => Yii::$app->places->city->id])->select('name, latitude, longitude')->all();
    }

    /**
     * Displays a single Place model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Finds the Place model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Place the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Place::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

backend/views/places/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\file\FileInput;
use himiklab\thumbnail\EasyThumbnailImage;
use kartik\select2\Select2;
use kartik\rating\StarRating;
use dosamigos\ckeditor\CKEditor;
use common\models\User;
use common\models\City;
use common\models\District;
use common\models\Place;
use common\models\Comfort;
use common\models\MetroStation;
use common\models\PlaceNetwork;

/* @var $this yii\web\View */
/* @var $model common\models\Place */
/* @var $form yii\widgets\ActiveForm */

$this->registerJsFile('https://api-maps.yandex.ru/2.1/?lang=ru_RU');
?>

<div class="place-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'class' => 'form-control alias-source']) ?>
    <?= $form->field($model, 'alias')->textInput(['maxlength' => true, 'class' => 'form-control alias-target']) ?>
	<?= $form->field($model, 'user_id')->widget(Select2::classname(), [
		'data' => ArrayHelper::map(User::find()->where(['role' => User::ROLE_OWNER])->all(), 'id', 'email'),
		'options' => ['placeholder' => 'Выберите владельца'],
		'pluginOptions' => [
			'allowClear' => true
		],
	]); ?>
	<?= $form->field($model, 'city_id')->widget(Select2::classname(), [
		'data' => ArrayHelper::map(City::find()->orderBy('name ASC')->all(), 'id', 'name'),
		'options' => ['placeholder' => 'Выберите город', 'class' => 'form-control city-select'],
		'pluginOptions' => [
			'allowClear' => true
		],
	]); ?>
    <?php if ($model->city_id): ?>
        <?= $form->field($model, 'district_id')->dropDownList(
            ArrayHelper::map(District::find()->where(['city_id' => $model->city_id])->orderBy('name ASC')->all(), 'id', 'name'),
            ['prompt' => 'Выберите район', 'class' => 'form-control district-select']
        ) ?>
    <?php else: ?>
        <?= $form->field($model, 'district_id')->dropDownList([], ['prompt' => 'Сперва выберите город', 'disabled' => true, 'class' => 'form-control district-select']) ?>
    <?php endif ?>
    <?php if ($model->city_id): ?>
        <?= $form->field($model, 'metro_field')->widget(Select2::classname(), [
            'data' => ArrayHelper::map(MetroStation::find()->where(['city_id' => $model->city_id])->orderBy('name ASC')->all(), 'id', 'name'),
            'options' => ['placeholder' => 'Выберите станции метро', 'class' => 'form-control metro-select', 'multiple' => true],
            'pluginOptions' => [
                'allowClear' => true,
                'maximumSelectionLength' => 3,
            ],
        ]); ?>
    <?php else: ?>
        <?= $form->field($model, 'metro_field')->dropDownList([], ['prompt' => 'Сперва выберите город', 'disabled' => true, 'class' => 'form-control metro-select']) ?>
    <?php endif ?>
    <div class="geo-block" <?= $model->isNewRecord ? 'style="display: none;"' : '' ?> >
        <?php $model->coordinates = $model->defaultCoordinates; ?>
        <?= $form->field($model, 'coordinates')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'latitude')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'longitude')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>
        <div id="place-map" data-coords="<?= $model->defaultCoordinates ?>"></div>
    </div>
    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'website')->textInput(['maxlength' => true]) ?>
	<?= $form->field($model, 'introtext')->widget(CKEditor::classname(), [
		'options' => ['rows' => 6],
		'preset' => 'full',
	]) ?>
	<?= $form->field($model, 'description')->widget(CKEditor::classname(), [
		'options' => ['rows' => 6],
		'preset' => 'full',
	]) ?>
    <?= $form->field($model, 'rating')->widget(StarRating::classname(), [
        'pluginOptions' => ['step' => 1, 'showClear' => false, 'displayOnly' => true]
    ]) ?>
    <?= $form->field($model, 'images_field[]')->widget(FileInput::classname(), [
        'options' => [
            'multiple' => true,
            'accept' => 'image/*'
        ],
        'pluginOptions' => [
            'browseLabel' => 'Выбрать',
            'showPreview' => false,
            'showUpload' => false,
            'showRemove' => false,
        ]
    ]); ?>
    <?php if (count($model->images)): ?>
        <ul id="sortable_photoes" class="photo-list" data-url="<?= Url::to(['sort-images']) ?>">
            <?php foreach ($model->images as $image): ?>
                <li data-id="<?= $image->id ?>">
                    <?= EasyThumbnailImage::thumbnailImg(Yii::getAlias('@frontend_web').$image->path, 160, 160, EasyThumbnailImage::THUMBNAIL_OUTBOUND) ?>
                    <?= Html::a('<span class="glyphicon glyphicon-repeat"></span>', ['rotate-image', 'id' => $image->id, 'angle' => 90], ['class' => 'btn btn-xs btn-primary rotate-image']) ?>
                    <?= Html::a('Удалить', ['delete-image', 'id' => $image->id], ['class' => 'btn btn-xs btn-danger delete-image']) ?>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endif ?>
    <?= $form->field($model, 'comforts_field')->checkboxList(ArrayHelper::map(Comfort::find()->all(), 'id', 'name')) ?>
    <?= $form->field($model, 'similar_field')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Place::find()->orderBy('name ASC')->all(), 'id', 'name'),
        'options' => ['placeholder' => 'Выберите заведения', 'multiple' => true],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]); ?>
    <?= $form->field($model, 'network_id')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(PlaceNetwork::find()->orderBy('name ASC')->all(), 'id', 'name'),
        'options' => ['placeholder' => 'Выберите сеть'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]) ?>
    <?= $form->field($model, 'total_views')->input('number') ?>
    <?= $form->field($model, 'total_likes')->input('number') ?>
    <?= $form->field($model, 'status')->dropDownList($model->statusArr) ?>
    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/views/places/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\PlacesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="place-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'alias') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'city_id') ?>

    <?php // echo $form->field($model, 'coordinates') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'website') ?>

    <?php // echo $form->field($model, 'introtext') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'rating') ?>

    <?php // echo $form->field($model, 'total_views') ?>

    <?php // echo $form->field($model, 'total_likes') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/places/_tabs.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Place */
?>

<ul class="nav nav-tabs">
    <li <?= Yii::$app->controller->action->id == 'view' ? 'class="active"' : '' ?> >
    	<a href="<?= Url::to(['places/view', 'id' => $model->id]) ?>">Общее</a>
    </li>
    <li <?= Yii::$app->controller->action->id == 'view-reviews' ? 'class="active"' : '' ?> >
    	<a href="<?= Url::to(['places/view-reviews', 'id' => $model->id]) ?>">Отзывы (<?= count($model->reviews) ?>)</a>
    </li>
    <li <?= Yii::$app->controller->action->id == 'opening-hours' ? 'class="active"' : '' ?> >
    	<a href="<?= Url::to(['places/opening-hours', 'id' => $model->id]) ?>">Часы работы</a>
    </li>
</ul>

backend/views/places/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Place */

$this->title = 'Добавление заведения';
$this->params['breadcrumbs'][] = ['label' => 'Заведения', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="place-create">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

backend/views/places/index.php
<?php

use common\models\City;
use common\models\User;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\PlacesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Заведения';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="place-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <p>
        <?= Html::a('Добавить заведение', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'name',
            'alias',
            [
                'attribute' => 'user_id',
                'format' => 'raw',
                'value' => function($data) {
                    return $data->user ? Html::a($data->user->name, ['users/view', 'id' => $data->user_id]) : '-';
                },
                'filter' => Html::activeDropDownList($searchModel, 'user_id', ArrayHelper::map(User::find()->orderBy('name ASC')->all(), 'id', 'name'), ['class' => 'form-control', 'prompt' => '']),
            ],
            [
                'attribute' => 'city_id',
                'format' => 'raw',
                'value' => function($data) {
                    return $data->city ? Html::a($data->city->name, ['cities/view', 'id' => $data->city_id]) : '-';
                },
                'filter' => Html::activeDropDownList($searchModel, 'city_id', ArrayHelper::map(City::find()->orderBy('name ASC')->all(), 'id', 'name'), ['class' => 'form-control', 'prompt' => '']),
            ],
            //'longitude',
            //'latitude',
            //'address',
            //'phone',
            //'website',
            //'introtext:ntext',
            //'description:ntext',
            //'rating',
            //'total_views',
            //'total_likes',
			[
				'attribute' => 'status',
				'format' => 'raw',
				'value' => function($data) {
					return $data->statusName;
				},
				'filter' => Html::activeDropDownList($searchModel, 'status', $searchModel->statusArr, ['class'=>'form-control', 'prompt' => 'Не важно']),
			],
            //'created_at',
            //'updated_at',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

backend/views/places/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Place */

$this->title = 'Редактирование заведения: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Заведения', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>

<div class="place-update">
    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>